# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a260fe3e7ccf6391f0176170d1e0bd29946f4ff55460aa28ac26cf38216802f25ac2f4acb393b3117fb0c729cc089204d568212295d687ba7fd0c0ea668152b

test:
  secret_key_base: ac94e1002e4fb495b9f7dd233432f8351e8311a8dc3190eca2f230097964c8e4060b0f7396ecb77f392108cecffb1831a7b8c685c9f03296cfaa4491337179e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
